modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/skyjay1/Nomadic-Tents/issues"

[[mods]]
    modId="nomadictents"
    version="16.5.1"
    displayName="Nomadic Tents"
    # multi line!
    description='''Adds portable houses to Minecraft!'''
    [[dependencies.nomadictents]]
        modId="forge"
        mandatory=true
        versionRange="[36.2,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.nomadictents]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16,]"
        ordering="NONE"
        side="BOTH"