# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[36,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/skyjay1/Nomadic-Tents/issues"

[[mods]]
    modId="nomadictents"
    version="16.5.0"
    displayName="Nomadic Tents"
    # multi line!
    description='''Adds portable houses to Minecraft!'''
    [[dependencies.nomadictents]]
        modId="forge"
        mandatory=true
        versionRange="[36.2,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.nomadictents]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16,]"
        ordering="NONE"
        side="BOTH"